// ═══ DATA CONSTANTS ═══
// INGDB (ingredient database), INGFLAT (flat lookup), LIB (quick-add presets)

const LIB=[
  {name:"Mojito",cat:"Classic",dpg:1,ing:[{n:"Havana Club 3 ans rum",q:1.5,u:"oz",c:1.18},{n:"Lime juice — fresh squeezed on site",q:0.75,u:"oz",c:0.18},{n:"Simple syrup (homemade)",q:0.5,u:"oz",c:0.05},{n:"Mint (fresh)",q:6,u:"leaves",c:0.02},{n:"Soda water",q:2,u:"oz",c:0.06}]},
  {name:"Aperol Spritz",cat:"Signature",dpg:1,ing:[{n:"Aperol",q:2,u:"oz",c:0.85},{n:"Prosecco (Cinzano)",q:3,u:"oz",c:0.63},{n:"Soda water",q:1,u:"oz",c:0.06},{n:"Orange slice",q:1,u:"piece",c:0.18}]},
  {name:"Margarita",cat:"Classic",dpg:1,ing:[{n:"Olmeca tequila blanco",q:2,u:"oz",c:1.50},{n:"Lime juice — fresh squeezed on site",q:1,u:"oz",c:0.18},{n:"Triple sec",q:0.5,u:"oz",c:0.71},{n:"Salt (rim)",q:1,u:"pinch",c:0.01}]},
  {name:"Gin & Tonic",cat:"Classic",dpg:1,ing:[{n:"Bombay Sapphire gin",q:1.5,u:"oz",c:1.50},{n:"Tonic water",q:4,u:"oz",c:0.22},{n:"Lime wedge",q:1,u:"piece",c:0.12}]},
  {name:"Cosmopolitan",cat:"Signature",dpg:1,ing:[{n:"Absolut vodka",q:1.5,u:"oz",c:1.30},{n:"Triple sec",q:0.5,u:"oz",c:0.71},{n:"Cranberry juice",q:1,u:"oz",c:0.12},{n:"Lime juice — fresh squeezed on site",q:0.5,u:"oz",c:0.10}]},
  {name:"Old Fashioned",cat:"Classic",dpg:1,ing:[{n:"Bourbon whiskey",q:2,u:"oz",c:1.42},{n:"Simple syrup (homemade)",q:0.25,u:"oz",c:0.05},{n:"Angostura bitters",q:2,u:"dashes",c:0.06},{n:"Orange peel",q:1,u:"piece",c:0.12}]},
  {name:"Moscow Mule",cat:"Classic",dpg:1,ing:[{n:"Absolut vodka",q:1.5,u:"oz",c:1.30},{n:"Ginger beer",q:4,u:"oz",c:0.40},{n:"Lime juice — fresh squeezed on site",q:0.5,u:"oz",c:0.10},{n:"Mint (fresh)",q:3,u:"leaves",c:0.02}]},
  {name:"Paloma",cat:"Classic",dpg:1,ing:[{n:"Olmeca tequila blanco",q:2,u:"oz",c:1.50},{n:"Grapefruit juice",q:2,u:"oz",c:0.22},{n:"Lime juice — fresh squeezed on site",q:0.5,u:"oz",c:0.10},{n:"Soda water",q:2,u:"oz",c:0.06},{n:"Salt (rim)",q:1,u:"pinch",c:0.01}]},
  {name:"Negroni",cat:"Classic",dpg:1,ing:[{n:"Bombay Sapphire gin",q:1,u:"oz",c:1.50},{n:"Campari",q:1,u:"oz",c:1.18},{n:"Sweet vermouth (Martini Rosso)",q:1,u:"oz",c:0.71},{n:"Orange peel",q:1,u:"piece",c:0.12}]},
  {name:"Espresso Martini",cat:"Signature",dpg:1,ing:[{n:"Absolut vodka",q:1.5,u:"oz",c:1.30},{n:"Kahlua",q:0.75,u:"oz",c:1.10},{n:"Espresso",q:1,u:"oz",c:0.35},{n:"Simple syrup (homemade)",q:0.25,u:"oz",c:0.05}]},
  {name:"Whisky Sour",cat:"Classic",dpg:1,ing:[{n:"Bourbon whiskey",q:2,u:"oz",c:1.42},{n:"Lemon juice — fresh squeezed on site",q:0.75,u:"oz",c:0.15},{n:"Simple syrup (homemade)",q:0.5,u:"oz",c:0.05},{n:"Egg white",q:0.5,u:"oz",c:0.12}]},
  {name:"Dark & Stormy",cat:"Classic",dpg:1,ing:[{n:"Gosling's Dark Seal rum",q:1.5,u:"oz",c:1.54},{n:"Ginger beer",q:4,u:"oz",c:0.40},{n:"Lime wedge",q:1,u:"piece",c:0.12}]},
  {name:"Sangria punch",cat:"Punch",dpg:1.5,ing:[{n:"Red wine (house)",q:3,u:"oz",c:0.50},{n:"Brandy",q:0.5,u:"oz",c:0.45},{n:"Orange juice (fresh)",q:1,u:"oz",c:0.12},{n:"Simple syrup (homemade)",q:0.5,u:"oz",c:0.05}]},
  {name:"Virgin Mojito",cat:"Non-alcoholic",dpg:1,ing:[{n:"Lime juice — fresh squeezed on site",q:1,u:"oz",c:0.18},{n:"Simple syrup (homemade)",q:0.5,u:"oz",c:0.05},{n:"Mint (fresh)",q:8,u:"leaves",c:0.02},{n:"Soda water",q:4,u:"oz",c:0.06}]},
  {name:"Shirley Temple",cat:"Non-alcoholic",dpg:1,ing:[{n:"Ginger ale",q:4,u:"oz",c:0.18},{n:"Grenadine",q:0.5,u:"oz",c:0.25},{n:"Orange juice (fresh)",q:1,u:"oz",c:0.12},{n:"Maraschino cherry",q:1,u:"piece",c:0.18}]},
  {name:"Yuzu Gin Fizz",cat:"Signature",dpg:1,ing:[{n:"Bombay Sapphire gin",q:1.5,u:"oz",c:1.50},{n:"Yuzu juice (bottled)",q:0.75,u:"oz",c:0.90},{n:"Simple syrup (homemade)",q:0.5,u:"oz",c:0.05},{n:"Soda water",q:2,u:"oz",c:0.06},{n:"Shiso leaf",q:1,u:"piece",c:0.15}]},
  {name:"Lychee Martini",cat:"Signature",dpg:1,ing:[{n:"Absolut vodka",q:1.5,u:"oz",c:1.30},{n:"Lychee liqueur (Soho)",q:0.75,u:"oz",c:1.26},{n:"Lychee juice",q:1,u:"oz",c:0.18},{n:"Lime juice — fresh squeezed on site",q:0.5,u:"oz",c:0.18},{n:"Lychee (canned, muddled)",q:1,u:"piece",c:0.20}]},
  {name:"Japanese Whisky Highball",cat:"Classic",dpg:1,ing:[{n:"Japanese whisky (Nikka/Suntory)",q:1.5,u:"oz",c:2.76},{n:"Soda water",q:4,u:"oz",c:0.06},{n:"Lemon wheel",q:1,u:"piece",c:0.08}]},
  {name:"Matcha Sake Spritz",cat:"Signature",dpg:1,ing:[{n:"Sake (dry/junmai)",q:2,u:"oz",c:0.79},{n:"Matcha syrup",q:0.5,u:"oz",c:0.40},{n:"Yuzu juice (bottled)",q:0.5,u:"oz",c:0.90},{n:"Soda water",q:2,u:"oz",c:0.06},{n:"Cucumber (Asian/seedless)",q:1,u:"piece",c:0.10}]},
  {name:"Spicy Yuzu Margarita",cat:"Signature",dpg:1,ing:[{n:"Olmeca tequila blanco",q:2,u:"oz",c:1.50},{n:"Yuzu juice (bottled)",q:0.75,u:"oz",c:0.90},{n:"Triple sec",q:0.5,u:"oz",c:0.71},{n:"Fresh ginger juice",q:0.25,u:"oz",c:0.30},{n:"Tajin (chili-lime rim)",q:1,u:"pinch",c:0.05}]},
  {name:"Butterfly Pea Gin Sour",cat:"Signature",dpg:1,ing:[{n:"Bombay Sapphire gin",q:1.5,u:"oz",c:1.50},{n:"Butterfly pea flower tea",q:1,u:"oz",c:0.10},{n:"Lemon juice — fresh squeezed on site",q:0.75,u:"oz",c:0.15},{n:"Simple syrup (homemade)",q:0.5,u:"oz",c:0.05},{n:"Egg white",q:0.5,u:"oz",c:0.12}]},
  {name:"Lemongrass Mule",cat:"Signature",dpg:1,ing:[{n:"Absolut vodka",q:1.5,u:"oz",c:1.30},{n:"Lemongrass syrup",q:0.5,u:"oz",c:0.25},{n:"Lime juice — fresh squeezed on site",q:0.5,u:"oz",c:0.18},{n:"Ginger beer",q:4,u:"oz",c:0.40},{n:"Lemongrass stalk",q:1,u:"piece",c:0.30}]},
];

let cocktails=[], nIng=[];
// ═══════════════════════════════════════════════════════════
// INGREDIENT DATABASE — organized by category
// Each entry: { name, unit, c (cost/unit CAD), note }
// ═══════════════════════════════════════════════════════════
const INGDB = {
  "🥃 Spirits — Whisky & Bourbon": [
    {name:"Johnnie Walker Black Label",unit:"oz",c:1.97,note:"~$50/750ml SAQ"},
    {name:"Johnnie Walker Red Label",unit:"oz",c:1.42,note:"~$36/750ml SAQ"},
    {name:"Johnnie Walker Double Black",unit:"oz",c:2.28,note:"~$58/750ml SAQ"},
    {name:"Jack Daniel's Tennessee",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Jack Daniel's Honey",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Jack Daniel's Fire",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Crown Royal Canadian",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Crown Royal Apple",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Crown Royal Peach",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Jim Beam bourbon",unit:"oz",c:1.14,note:"~$29/750ml SAQ"},
    {name:"Maker's Mark bourbon",unit:"oz",c:1.81,note:"~$46/750ml SAQ"},
    {name:"Bulleit bourbon",unit:"oz",c:1.73,note:"~$44/750ml SAQ"},
    {name:"Bulleit rye",unit:"oz",c:1.73,note:"~$44/750ml SAQ"},
    {name:"Woodford Reserve bourbon",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Jameson Irish whiskey",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Jameson Black Barrel",unit:"oz",c:1.89,note:"~$48/750ml SAQ"},
    {name:"Glenfiddich 12yr",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Laphroaig 10yr",unit:"oz",c:2.56,note:"~$65/750ml SAQ"},
    {name:"Glenlivet 12yr",unit:"oz",c:2.09,note:"~$53/750ml SAQ"},
    {name:"Canadian Club whisky",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Forty Creek Canadian whisky",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"Gibson's Finest",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Wiser's Deluxe Canadian whisky",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Wild Turkey 101 bourbon",unit:"oz",c:1.46,note:"~$37/750ml SAQ"},
  ],  "🍸 Spirits — Vodka": [
    {name:"Absolut vodka",unit:"oz",c:1.30,note:"~$33/750ml SAQ"},
    {name:"Absolut Citron",unit:"oz",c:1.34,note:"~$34/750ml SAQ"},
    {name:"Absolut Raspberri",unit:"oz",c:1.34,note:"~$34/750ml SAQ"},
    {name:"Absolut Vanilia",unit:"oz",c:1.34,note:"~$34/750ml SAQ"},
    {name:"Grey Goose vodka",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Grey Goose La Poire",unit:"oz",c:2.28,note:"~$58/750ml SAQ"},
    {name:"Grey Goose L'Orange",unit:"oz",c:2.28,note:"~$58/750ml SAQ"},
    {name:"Grey Goose Le Citron",unit:"oz",c:2.28,note:"~$58/750ml SAQ"},
    {name:"Belvedere vodka",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Belvedere Peach Nectar",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Belvedere Wild Berry",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Stolichnaya vodka",unit:"oz",c:1.38,note:"~$35/750ml SAQ"},
    {name:"Stolichnaya Vanil",unit:"oz",c:1.42,note:"~$36/750ml SAQ"},
    {name:"Stolichnaya Razberi",unit:"oz",c:1.42,note:"~$36/750ml SAQ"},
    {name:"Tito's vodka",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Ketel One vodka",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Ketel One Botanical Cucumber Mint",unit:"oz",c:1.69,note:"~$43/750ml SAQ"},
    {name:"Ketel One Botanical Peach Orange Blossom",unit:"oz",c:1.69,note:"~$43/750ml SAQ"},
    {name:"Russian Standard vodka",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"Ciroc vodka",unit:"oz",c:1.97,note:"~$50/750ml SAQ"},
    {name:"Ciroc Red Berry",unit:"oz",c:2.05,note:"~$52/750ml SAQ"},
    {name:"Ciroc Peach",unit:"oz",c:2.05,note:"~$52/750ml SAQ"},
    {name:"Ciroc Coconut",unit:"oz",c:2.05,note:"~$52/750ml SAQ"},
    {name:"Smirnoff vodka",unit:"oz",c:0.94,note:"~$24/750ml SAQ"},
    {name:"Smirnoff Raspberry",unit:"oz",c:0.98,note:"~$25/750ml SAQ"},
    {name:"Finlandia vodka",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"42 Below vodka",unit:"oz",c:1.50,note:"~$38/750ml SAQ"},
    {name:"UV Blue vodka (raspberry)",unit:"oz",c:1.06,note:"~$27/750ml SAQ"},
    {name:"Local/house vodka",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
  ],
  "🌿 Spirits — Gin": [
    {name:"Bombay Sapphire gin",unit:"oz",c:1.50,note:"~$38/750ml SAQ"},
    {name:"Bombay Sapphire East",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Hendrick's gin",unit:"oz",c:1.97,note:"~$50/750ml SAQ"},
    {name:"Hendrick's Lunar gin",unit:"oz",c:2.09,note:"~$53/750ml SAQ"},
    {name:"Hendrick's Neptunia gin",unit:"oz",c:2.09,note:"~$53/750ml SAQ"},
    {name:"Tanqueray gin",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Tanqueray No. Ten gin",unit:"oz",c:1.89,note:"~$48/750ml SAQ"},
    {name:"Ungava gin (QC)",unit:"oz",c:1.73,note:"~$44/750ml SAQ — local Quebec"},
    {name:"Empress 1908 gin",unit:"oz",c:2.05,note:"~$52/750ml SAQ — purple, Instagram-worthy"},
    {name:"Roku gin",unit:"oz",c:1.81,note:"~$46/750ml SAQ"},
    {name:"The Botanist gin",unit:"oz",c:2.09,note:"~$53/750ml SAQ"},
    {name:"Malfy Limone gin",unit:"oz",c:1.89,note:"~$48/750ml SAQ"},
    {name:"Malfy Rosa gin",unit:"oz",c:1.89,note:"~$48/750ml SAQ"},
    {name:"Monkey 47 gin",unit:"oz",c:3.15,note:"~$80/500ml SAQ"},
    {name:"Beefeater gin",unit:"oz",c:1.38,note:"~$35/750ml SAQ"},
    {name:"The Botanist gin",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Roku gin",unit:"oz",c:1.77,note:"~$45/750ml SAQ"},
    {name:"Aviation gin",unit:"oz",c:1.77,note:"~$45/750ml SAQ"},
    {name:"Local/house gin",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"Boreal Gin (QC)",unit:"oz",c:2.17,note:"~$55/750ml SAQ — Quebec local"},
    {name:"Cirka Gin no. 7 (QC)",unit:"oz",c:1.85,note:"~$47/750ml SAQ — Quebec local"},
    {name:"Fecteau Gin (QC)",unit:"oz",c:1.93,note:"~$49/750ml SAQ — Quebec local"},
  ],
  "🌵 Spirits — Tequila & Mezcal": [
    {name:"Patron Silver tequila",unit:"oz",c:2.76,note:"~$70/750ml SAQ"},
    {name:"Patron Reposado tequila",unit:"oz",c:2.96,note:"~$75/750ml SAQ"},
    {name:"Patron Anejo tequila",unit:"oz",c:3.35,note:"~$85/750ml SAQ"},
    {name:"Don Julio Blanco",unit:"oz",c:2.96,note:"~$75/750ml SAQ"},
    {name:"Don Julio Reposado",unit:"oz",c:3.15,note:"~$80/750ml SAQ"},
    {name:"Don Julio 1942",unit:"oz",c:7.88,note:"~$200/750ml SAQ — premium"},
    {name:"Jose Cuervo Gold",unit:"oz",c:1.30,note:"~$33/750ml SAQ"},
    {name:"Jose Cuervo Silver",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"1800 Silver tequila",unit:"oz",c:1.65,note:"~$42/750ml SAQ"},
    {name:"1800 Coconut tequila",unit:"oz",c:1.73,note:"~$44/750ml SAQ"},
    {name:"Herradura Silver",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Olmeca Altos Plata",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Espolon Blanco",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"El Jimador Blanco",unit:"oz",c:1.38,note:"~$35/750ml SAQ"},
    {name:"Casamigos Blanco",unit:"oz",c:2.76,note:"~$70/750ml SAQ"},
    {name:"Casamigos Reposado",unit:"oz",c:2.96,note:"~$75/750ml SAQ"},
    {name:"Del Maguey Vida mezcal",unit:"oz",c:3.15,note:"~$80/750ml SAQ"},
    {name:"Montelobos mezcal",unit:"oz",c:2.56,note:"~$65/750ml SAQ"},
  ],  "🍹 Spirits — Rum": [
    {name:"Havana Club 3 ans rum",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"Havana Club 7 ans rum",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Diplomatico Reserva rum",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Appleton Estate rum",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
    {name:"Mount Gay Eclipse rum",unit:"oz",c:1.46,note:"~$37/750ml SAQ"},
    {name:"Malibu coconut rum",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Gosling's Dark Seal rum",unit:"oz",c:1.54,note:"~$39/750ml SAQ"},
    {name:"Plantation rum",unit:"oz",c:1.77,note:"~$45/750ml SAQ"},
    {name:"Overproof white rum",unit:"oz",c:1.30,note:"~$33/750ml SAQ"},
    {name:"Bacardi Superior white rum",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"Bacardi Limón",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"Bacardi Coconut",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"Bacardi Spiced",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"Myers's Dark rum",unit:"oz",c:1.34,note:"~$34/750ml SAQ"},
  ],
  "🍊 Liqueurs & Aperitifs": [
    {name:"Aperol",unit:"oz",c:0.85,note:"~$21.45/750ml SAQ"},
    {name:"Campari",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"Cointreau",unit:"oz",c:1.58,note:"~$40/750ml SAQ"},
    {name:"Triple sec",unit:"oz",c:0.71,note:"~$18/750ml SAQ"},
    {name:"Grand Marnier",unit:"oz",c:1.77,note:"~$45/750ml SAQ"},
    {name:"Kahlua",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Baileys Irish Cream",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Amaretto (Disaronno)",unit:"oz",c:1.38,note:"~$35/750ml SAQ"},
    {name:"Frangelico",unit:"oz",c:1.50,note:"~$38/750ml SAQ"},
    {name:"Chambord",unit:"oz",c:1.77,note:"~$45/750ml SAQ"},
    {name:"St-Germain elderflower",unit:"oz",c:1.77,note:"~$45/750ml SAQ"},
    {name:"Peach schnapps",unit:"oz",c:0.79,note:"~$20/750ml SAQ"},
    {name:"Blue Curaçao",unit:"oz",c:0.87,note:"~$22/750ml SAQ"},
    {name:"Midori melon",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Limoncello",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Amaretto",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"Pimm's No.1",unit:"oz",c:1.30,note:"~$33/750ml SAQ"},
    {name:"Lillet Blanc",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
  ],
  "🥃 Brandy & Cognac": [
    {name:"Hennessy VS cognac",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Hennessy VSOP cognac",unit:"oz",c:3.54,note:"~$90/750ml SAQ"},
    {name:"Remy Martin VSOP",unit:"oz",c:2.96,note:"~$75/750ml SAQ"},
    {name:"Courvoisier VS cognac",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Martell VS cognac",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Armagnac Janneau VS",unit:"oz",c:1.97,note:"~$50/750ml SAQ"},
    {name:"Calvados (apple brandy)",unit:"oz",c:2.17,note:"~$55/750ml SAQ"},
    {name:"Pisco Capel",unit:"oz",c:1.73,note:"~$44/750ml SAQ"},
    {name:"Christian Brothers brandy",unit:"oz",c:1.06,note:"~$27/750ml SAQ"},
  ],
  "🍷 Vermouth & Fortified Wine": [
    {name:"Sweet vermouth (Martini Rosso)",unit:"oz",c:0.71,note:"~$18/750ml SAQ"},
    {name:"Dry vermouth (Martini Extra Dry)",unit:"oz",c:0.67,note:"~$17/750ml SAQ"},
    {name:"Campari",unit:"oz",c:1.18,note:"~$30/750ml SAQ"},
    {name:"Aperol",unit:"oz",c:0.85,note:"~$21.45/750ml SAQ"},
    {name:"Dubonnet",unit:"oz",c:0.95,note:"~$24/750ml SAQ"},
    {name:"Sherry (Fino)",unit:"oz",c:0.95,note:"~$24/750ml SAQ"},
    {name:"Port wine",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
  ],
  "🍾 Wine & Bubbles": [
    {name:"Prosecco (Cinzano)",unit:"oz",c:0.63,note:"~$16/750ml SAQ"},
    {name:"Champagne (entry level)",unit:"oz",c:1.58,note:"~$40/750ml SAQ"},
    {name:"Sparkling wine (Cava)",unit:"oz",c:0.71,note:"~$18/750ml SAQ"},
    {name:"Red wine (house)",unit:"oz",c:0.50,note:"~$13/750ml SAQ"},
    {name:"White wine (house)",unit:"oz",c:0.50,note:"~$13/750ml SAQ"},
    {name:"Rosé wine",unit:"oz",c:0.59,note:"~$15/750ml SAQ"},
  ],
  "🍺 Beer & Cider": [
    {name:"Domestic beer",unit:"bottle",c:2.50,note:"~$2.50 retail"},
    {name:"Craft beer (local)",unit:"bottle",c:4.00,note:"~$4 retail"},
    {name:"Hard cider",unit:"bottle",c:3.50,note:"~$3.50 retail"},
    {name:"Radler/shandy",unit:"can",c:2.75,note:"~$2.75 retail"},
  ],
  "🌊 Mixers & Sodas": [
    {name:"Soda water",unit:"oz",c:0.06,note:"~$2/1L grocery"},
    {name:"Tonic water",unit:"oz",c:0.22,note:"~$7/1L premium grocery"},
    {name:"Ginger beer",unit:"oz",c:0.40,note:"~$5/355ml can grocery"},
    {name:"Ginger ale",unit:"oz",c:0.18,note:"~$2/1L grocery"},
    {name:"Cola (Coca-Cola)",unit:"oz",c:0.12,note:"~$2.50/2L grocery"},
    {name:"Diet cola",unit:"oz",c:0.12,note:"~$2.50/2L grocery"},
    {name:"Lemon-lime soda (Sprite)",unit:"oz",c:0.12,note:"~$2.50/2L grocery"},
    {name:"Grapefruit soda",unit:"oz",c:0.18,note:"~$4/1L grocery"},
    {name:"Cream soda",unit:"oz",c:0.12,note:"~$2.50/2L grocery"},
    {name:"Still water",unit:"oz",c:0.04,note:"~$3/2L grocery"},
  ],
  "🍋 Juices": [
    {name:"Lime juice — fresh squeezed on site",unit:"oz",c:0.18,note:"~$0.75/lime · 1 lime = ~1oz juice · squeeze at event"},
    {name:"Lime juice — pre-batched fresh",unit:"oz",c:0.18,note:"~$0.75/lime · squeezed in advance, brought in container"},
    {name:"Lime juice — bottled (Bottled lime juice)",unit:"oz",c:0.06,note:"~$4.50/250ml bottle IGA/Metro · ~$0.06/oz"},
    {name:"Lime juice — bottled (Roses)",unit:"oz",c:0.07,note:"~$5/250ml bottle IGA/Metro · sweetened, lower quality"},
    {name:"Lemon juice — fresh squeezed on site",unit:"oz",c:0.15,note:"~$0.60/lemon · 1 lemon = ~1.5oz juice · squeeze at event"},
    {name:"Lemon juice — pre-batched fresh",unit:"oz",c:0.15,note:"~$0.60/lemon · squeezed in advance, brought in container"},
    {name:"Lemon juice — bottled (RealLemon)",unit:"oz",c:0.05,note:"~$4/250ml bottle IGA/Metro · ~$0.05/oz"},
    {name:"Orange juice (fresh)",unit:"oz",c:0.12,note:"~$4/1L grocery"},
    {name:"Grapefruit juice",unit:"oz",c:0.22,note:"~$5/1L grocery"},
    {name:"Cranberry juice",unit:"oz",c:0.12,note:"~$4/1L grocery"},
    {name:"Pineapple juice",unit:"oz",c:0.14,note:"~$3.50/1L grocery"},
    {name:"Mango juice",unit:"oz",c:0.18,note:"~$5/1L grocery"},
    {name:"Tomato juice",unit:"oz",c:0.10,note:"~$3/1L grocery"},
    {name:"Clamato juice",unit:"oz",c:0.08,note:"~$4/1.89L Aubut — Quebec Caesar"},
    {name:"Walter Caesar mix",unit:"oz",c:0.12,note:"~$6/1L Aubut/SAQ"},
    {name:"Coconut water",unit:"oz",c:0.20,note:"~$5/1L grocery"},
    {name:"Apple juice",unit:"oz",c:0.08,note:"~$3/1L grocery"},
    {name:"Passion fruit juice",unit:"oz",c:0.22,note:"~$5/1L grocery"},
  ],
  "🍯 Syrups & Sweeteners": [
    {name:"Simple syrup (homemade)",unit:"oz",c:0.05,note:"~sugar + water"},
    {name:"Simple syrup (commercial)",unit:"oz",c:0.15,note:"~$6/750ml"},
    {name:"Grenadine",unit:"oz",c:0.25,note:"~$6/750ml grocery"},
    {name:"Agave nectar",unit:"oz",c:0.20,note:"~$6/250ml grocery"},
    {name:"Honey syrup",unit:"oz",c:0.18,note:"~$5/250ml grocery"},
    {name:"Lavender syrup",unit:"oz",c:0.30,note:"~$9/250ml specialty"},
    {name:"Rose syrup",unit:"oz",c:0.30,note:"~$9/250ml specialty"},
    {name:"Orgeat (almond syrup)",unit:"oz",c:0.35,note:"~$10/375ml SAQ"},
    {name:"Falernum",unit:"oz",c:0.35,note:"~$10/375ml SAQ"},
    {name:"Passion fruit syrup",unit:"oz",c:0.30,note:"~$9/250ml specialty"},
    {name:"Raspberry syrup",unit:"oz",c:0.28,note:"~$8/250ml grocery"},
    {name:"Vanilla syrup",unit:"oz",c:0.25,note:"~$7/250ml grocery"},
    {name:"Demerara syrup",unit:"oz",c:0.10,note:"~$4/250ml homemade"},
    {name:"Cane sugar syrup",unit:"oz",c:0.08,note:"~$3/250ml homemade"},
  ],
  "🌶 Bitters & Accents": [
    {name:"Angostura bitters",unit:"dashes",c:0.06,note:"~$12/200ml SAQ"},
    {name:"Peychaud's bitters",unit:"dashes",c:0.06,note:"~$12/200ml SAQ"},
    {name:"Orange bitters",unit:"dashes",c:0.06,note:"~$12/200ml SAQ"},
    {name:"Mole bitters",unit:"dashes",c:0.08,note:"~$15/100ml specialty"},
    {name:"Celery bitters",unit:"dashes",c:0.08,note:"~$15/100ml specialty"},
    {name:"Aromatic bitters",unit:"dashes",c:0.06,note:"~$12/200ml SAQ"},
    {name:"Tabasco sauce",unit:"dashes",c:0.03,note:"grocery"},
    {name:"Worcestershire sauce",unit:"dashes",c:0.03,note:"grocery"},
  ],
  "🍊 Garnishes — Citrus": [
    {name:"Lime wedge",unit:"piece",c:0.12,note:"~$0.50/lime grocery"},
    {name:"Lemon wedge",unit:"piece",c:0.10,note:"~$0.40/lemon grocery"},
    {name:"Orange slice",unit:"piece",c:0.18,note:"~$0.75/orange grocery"},
    {name:"Grapefruit slice",unit:"piece",c:0.20,note:"~$0.80/grapefruit grocery"},
    {name:"Lime wheel",unit:"piece",c:0.10,note:"~$0.50/lime grocery"},
    {name:"Lemon wheel",unit:"piece",c:0.08,note:"~$0.40/lemon grocery"},
    {name:"Orange peel",unit:"piece",c:0.12,note:"~$0.75/orange grocery"},
    {name:"Lemon twist",unit:"piece",c:0.08,note:"~$0.40/lemon grocery"},
    {name:"Lime juice — fresh squeezed on site",unit:"oz",c:0.18,note:"~$0.75/lime · squeeze at event"},
  ],
  "🌿 Garnishes — Herbs & Other": [
    {name:"Mint (fresh)",unit:"leaves",c:0.02,note:"~$3/bunch grocery"},
    {name:"Basil (fresh)",unit:"leaves",c:0.03,note:"~$3/bunch grocery"},
    {name:"Rosemary sprig",unit:"piece",c:0.15,note:"~$3/bunch grocery"},
    {name:"Thyme sprig",unit:"piece",c:0.10,note:"~$3/bunch grocery"},
    {name:"Cucumber slice",unit:"piece",c:0.08,note:"~$2/cucumber grocery"},
    {name:"Celery stalk",unit:"piece",c:0.25,note:"~$3/bunch grocery"},
    {name:"Maraschino cherry",unit:"piece",c:0.18,note:"~$5/jar grocery"},
    {name:"Luxardo cherry",unit:"piece",c:0.60,note:"~$18/jar specialty"},
    {name:"Olive (cocktail)",unit:"piece",c:0.20,note:"~$5/jar grocery"},
    {name:"Cocktail onion",unit:"piece",c:0.15,note:"~$4/jar grocery"},
    {name:"Pineapple chunk",unit:"piece",c:0.20,note:"~$4/pineapple grocery"},
    {name:"Dried orange wheel",unit:"piece",c:0.35,note:"~$10/bag specialty"},
    {name:"Edible flower",unit:"piece",c:0.50,note:"~$8/pack specialty"},
    {name:"Cinnamon stick",unit:"piece",c:0.15,note:"~$4/pack grocery"},
    {name:"Star anise",unit:"piece",c:0.12,note:"~$4/pack grocery"},
    {name:"Dehydrated lime wheel",unit:"piece",c:0.40,note:"~$12/bag specialty"},
  ],
  "🧂 Salts, Sugars & Rims": [
    {name:"Salt (rim)",unit:"pinch",c:0.01,note:"grocery"},
    {name:"Sugar (rim)",unit:"pinch",c:0.01,note:"grocery"},
    {name:"Tajin (chili-lime rim)",unit:"pinch",c:0.05,note:"~$5/bottle grocery"},
    {name:"Smoked salt",unit:"pinch",c:0.05,note:"~$6/bottle specialty"},
    {name:"Celery salt",unit:"pinch",c:0.03,note:"~$4/bottle grocery"},
    {name:"Black pepper",unit:"pinch",c:0.02,note:"grocery"},
    {name:"Cayenne pepper",unit:"pinch",c:0.02,note:"grocery"},
  ],
  "🥚 Dairy & Proteins": [
    {name:"Egg white",unit:"oz",c:0.12,note:"~$4/dozen grocery"},
    {name:"Whole egg",unit:"piece",c:0.30,note:"~$4/dozen grocery"},
    {name:"Heavy cream",unit:"oz",c:0.20,note:"~$4/500ml grocery"},
    {name:"Coconut cream",unit:"oz",c:0.22,note:"~$3/400ml can grocery"},
    {name:"Condensed milk",unit:"oz",c:0.15,note:"~$3/300ml grocery"},
    {name:"Butter (fat-washed)",unit:"oz",c:0.18,note:"~$5/250g grocery"},
  ],
  "☕ Coffee & Tea": [
    {name:"Espresso",unit:"oz",c:0.35,note:"~$0.35/shot"},
    {name:"Cold brew coffee",unit:"oz",c:0.20,note:"~$6/1L grocery"},
    {name:"Black tea (brewed)",unit:"oz",c:0.05,note:"grocery"},
    {name:"Green tea (brewed)",unit:"oz",c:0.05,note:"grocery"},
    {name:"Matcha powder",unit:"tsp",c:0.40,note:"~$15/100g specialty"},
    {name:"Chai concentrate",unit:"oz",c:0.20,note:"~$6/1L grocery"},
  ],
  "🍵 Asian-Inspired": [
    {name:"Yuzu juice (bottled)",unit:"oz",c:0.90,note:"~$12/200ml · Japanese citrus · Ares/Marché TAU Montreal"},
    {name:"Yuzu juice (fresh)",unit:"oz",c:1.50,note:"~$3-4/yuzu · seasonal · Asian grocery MTL"},
    {name:"Yuzu kosho paste",unit:"tsp",c:0.40,note:"~$8/jar · spicy citrus condiment · Asian grocery"},
    {name:"Lychee juice",unit:"oz",c:0.18,note:"~$3/400ml can · IGA/Asian grocery"},
    {name:"Lychee liqueur (Soho)",unit:"oz",c:1.26,note:"~$32/750ml SAQ"},
    {name:"Sake (dry/junmai)",unit:"oz",c:0.79,note:"~$20/750ml SAQ"},
    {name:"Sake (nigori/cloudy)",unit:"oz",c:0.95,note:"~$24/750ml SAQ"},
    {name:"Plum wine (umeshu)",unit:"oz",c:0.95,note:"~$24/750ml SAQ"},
    {name:"Shochu",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Japanese whisky (Nikka/Suntory)",unit:"oz",c:2.76,note:"~$70/750ml SAQ"},
    {name:"Sesame oil (few drops)",unit:"dashes",c:0.05,note:"~$5/bottle grocery · fat wash or garnish"},
    {name:"Miso syrup (homemade)",unit:"oz",c:0.20,note:"~miso + simple syrup"},
    {name:"Ginger syrup",unit:"oz",c:0.25,note:"~$7/250ml · Asian grocery or homemade"},
    {name:"Fresh ginger juice",unit:"oz",c:0.30,note:"~$2/knob ginger · pressed fresh"},
    {name:"Matcha syrup",unit:"oz",c:0.40,note:"~matcha + simple syrup · specialty"},
    {name:"Matcha powder",unit:"tsp",c:0.40,note:"~$15/100g · specialty grocery"},
    {name:"Thai basil",unit:"leaves",c:0.04,note:"~$3/bunch · Asian grocery MTL"},
    {name:"Shiso leaf",unit:"piece",c:0.15,note:"~$4/pack · Asian grocery MTL"},
    {name:"Lemongrass stalk",unit:"piece",c:0.30,note:"~$3/bunch · Asian grocery MTL"},
    {name:"Lemongrass syrup",unit:"oz",c:0.25,note:"~homemade or specialty"},
    {name:"Kaffir lime leaf",unit:"piece",c:0.10,note:"~$3/pack · Asian grocery MTL"},
    {name:"Coconut water (fresh young coconut)",unit:"oz",c:0.35,note:"~$4/coconut · Asian grocery MTL"},
    {name:"Pandan syrup",unit:"oz",c:0.25,note:"~$5/bottle · Asian grocery MTL"},
    {name:"Tamarind syrup",unit:"oz",c:0.20,note:"~$4/bottle · Asian grocery MTL"},
    {name:"Black sesame syrup",unit:"oz",c:0.35,note:"~homemade or specialty"},
    {name:"Oolong tea (brewed)",unit:"oz",c:0.06,note:"~$8/100g tea · Asian grocery"},
    {name:"Jasmine tea (brewed)",unit:"oz",c:0.05,note:"~$6/100g tea · grocery"},
    {name:"Butterfly pea flower tea",unit:"oz",c:0.10,note:"~$10/50g · colour-changing · specialty"},
    {name:"Ramune soda",unit:"oz",c:0.20,note:"~$3/bottle · Asian grocery MTL"},
    {name:"Calpico (plain)",unit:"oz",c:0.18,note:"~$5/500ml · Asian grocery MTL"},
    {name:"Calpico (strawberry/melon)",unit:"oz",c:0.20,note:"~$5/500ml · Asian grocery MTL"},
    {name:"Mango lassi base",unit:"oz",c:0.15,note:"~$4/1L · Indian grocery MTL"},
    {name:"Rose water",unit:"dashes",c:0.05,note:"~$5/100ml · Middle Eastern/Asian grocery"},
    {name:"Lychee (canned, muddled)",unit:"piece",c:0.20,note:"~$3/400ml can · IGA/Asian grocery"},
    {name:"Cucumber (Asian/seedless)",unit:"piece",c:0.10,note:"~$2 · grocery"},
    {name:"Wasabi (small amount, rim)",unit:"pinch",c:0.08,note:"~$5/tube · grocery"},
    {name:"Soy sauce (savoury cocktail)",unit:"dashes",c:0.03,note:"grocery"},
    {name:"Mirin",unit:"oz",c:0.15,note:"~$5/300ml · Asian grocery MTL"},
  ],
  "🛒 Aubut — Bar Supplies": [
    {name:"Monin syrup (assorted)",unit:"oz",c:0.28,note:"~$14/750ml Aubut — syrups, 60+ flavors"},
    {name:"Monin Grenadine syrup",unit:"oz",c:0.28,note:"~$14/750ml Aubut"},
    {name:"Monin Blue Curaçao syrup",unit:"oz",c:0.28,note:"~$14/750ml Aubut"},
    {name:"Monin Passion Fruit syrup",unit:"oz",c:0.28,note:"~$14/750ml Aubut"},
    {name:"Monin Elderflower syrup",unit:"oz",c:0.28,note:"~$14/750ml Aubut"},
    {name:"Monin Simple syrup",unit:"oz",c:0.20,note:"~$10/750ml Aubut"},
    {name:"Monin Coconut syrup",unit:"oz",c:0.28,note:"~$14/750ml Aubut"},
    {name:"Monin Vanilla syrup",unit:"oz",c:0.28,note:"~$14/750ml Aubut"},
    {name:"Clamato juice",unit:"oz",c:0.08,note:"~$7/1.89L Aubut — Caesar essential"},
    {name:"Walter Caesar mix",unit:"oz",c:0.14,note:"~$7/946ml Aubut"},
    {name:"Fever-Tree tonic water",unit:"oz",c:0.18,note:"~$9/4×200ml Aubut"},
    {name:"Fever-Tree ginger beer",unit:"oz",c:0.18,note:"~$9/4×200ml Aubut"},
    {name:"Fever-Tree ginger ale",unit:"oz",c:0.18,note:"~$9/4×200ml Aubut"},
    {name:"Schweppes tonic water (Aubut)",unit:"oz",c:0.06,note:"~$6/2L Aubut"},
    {name:"Canada Dry ginger ale (Aubut)",unit:"oz",c:0.05,note:"~$5/2L Aubut"},
    {name:"SanPellegrino sparkling water",unit:"oz",c:0.10,note:"~$8/6×250ml Aubut"},
    {name:"Perrier sparkling water (Aubut)",unit:"oz",c:0.09,note:"~$7/6×330ml Aubut"},
    {name:"Lime juice (Rose's cordial)",unit:"oz",c:0.16,note:"~$6/500ml Aubut"},
    {name:"Lemon juice (bottled Realemon)",unit:"oz",c:0.10,note:"~$4/500ml Aubut"},
    {name:"Pineapple juice (Del Monte)",unit:"oz",c:0.07,note:"~$4/1.36L Aubut"},
    {name:"Cranberry juice cocktail",unit:"oz",c:0.08,note:"~$5/1.89L Aubut"},
    {name:"Orange juice (Fairlee)",unit:"oz",c:0.06,note:"~$5/1.89L Aubut"},
    {name:"Grapefruit juice",unit:"oz",c:0.08,note:"~$4/1L Aubut"},
    {name:"Coconut cream (Coco Lopez)",unit:"oz",c:0.35,note:"~$6/425ml can Aubut"},
    {name:"Tabasco sauce",unit:"dashes",c:0.05,note:"~$4/150ml Aubut"},
    {name:"Worcestershire sauce",unit:"dashes",c:0.03,note:"~$3/250ml Aubut"},
    {name:"Cocktail olives (jar)",unit:"piece",c:0.12,note:"~$5/jar Aubut — garnish"},
    {name:"Maraschino cherries",unit:"piece",c:0.15,note:"~$5/jar Aubut — garnish"},
    {name:"Cocktail picks / skewers",unit:"piece",c:0.02,note:"~$3/100pk Aubut — garnish"},
    {name:"Plastic cups 16oz",unit:"piece",c:0.08,note:"~$8/100pk Aubut — supplies"},
    {name:"Cocktail napkins",unit:"piece",c:0.02,note:"~$4/200pk Aubut — supplies"},
    {name:"Straws (cocktail)",unit:"piece",c:0.01,note:"~$3/250pk Aubut — supplies"},
    {name:"Disposable bar cups 12oz",unit:"piece",c:0.06,note:"~$6/100pk Aubut"},
  ],
  "🫙 Specialty & Misc": [
    {name:"Coconut milk",unit:"oz",c:0.15,note:"~$3/400ml can grocery"},
    {name:"Coconut water",unit:"oz",c:0.20,note:"~$5/1L grocery"},
    {name:"Almond milk",unit:"oz",c:0.10,note:"~$4/1L grocery"},
    {name:"Oat milk",unit:"oz",c:0.12,note:"~$5/1L grocery"},
    {name:"Club soda",unit:"oz",c:0.06,note:"~$2/1L grocery"},
    {name:"Fever-Tree tonic water",unit:"oz",c:0.18,note:"~$8/4\xd7200ml Aubut/IGA"},
    {name:"Fever-Tree ginger beer",unit:"oz",c:0.18,note:"~$8/4\xd7200ml Aubut"},
    {name:"Schweppes tonic water",unit:"oz",c:0.06,note:"~$3/1L Aubut"},
    {name:"Canada Dry ginger ale",unit:"oz",c:0.05,note:"~$2.50/1L Aubut"},
    {name:"Sparkling water (Perrier)",unit:"oz",c:0.15,note:"~$5/1L grocery"},
    {name:"Rose water",unit:"dashes",c:0.05,note:"~$5/100ml grocery"},
    {name:"Orange flower water",unit:"dashes",c:0.05,note:"~$5/100ml grocery"},
    {name:"Velvet Falernum",unit:"oz",c:0.35,note:"~$10/375ml SAQ"},
    {name:"Absinthe",unit:"oz",c:2.37,note:"~$60/750ml SAQ"},
    {name:"Midori",unit:"oz",c:1.10,note:"~$28/750ml SAQ"},
    {name:"Galliano",unit:"oz",c:1.38,note:"~$35/750ml SAQ"},
    {name:"Chartreuse (Green)",unit:"oz",c:2.76,note:"~$70/750ml SAQ"},
    {name:"Benedictine",unit:"oz",c:1.58,note:"~$40/750ml SAQ"},
    {name:"Drambuie",unit:"oz",c:1.62,note:"~$41/750ml SAQ"},
  ],
};

// flat list for search — built from INGDB + user custom DB
const INGFLAT = [];
Object.entries(INGDB).forEach(([cat, items]) => {
  items.forEach(item => INGFLAT.push({...item, cat}));
});
